//index.js
//获取应用实例
const app = getApp()

Page({
  data: {
    isScroll:true,
    tabIndex:0,
    istap:false,
    Tab:0,
    showMore:false,
    showAre:false,
    showPrice:false,
    showHouse:false,
    toView: 'banner',
    h:wx.getSystemInfoSync().windowHeight,
    
    moreTitle:[
      {
        content:"物业类型",
        subTitle:[
          "住宅","商住","别墅"
        ]
      },
      {
        content:"面积",
        subTitle:[
          "60","80","100"
        ]
      }
    ],
    areTitle:[
      {
        content:"区域",
        subTitle:[
          "不限","滨海新区","西青","武清","东丽","津南"
          ,"河东","北辰","河西"
        ]
      },
      {
        content:"地铁",
        subTitle:[
          "1号线","2号线","3号线","4号线","5号线","6号线","9号线"
        ]
      }
    ],
    priceTitle:[
      {
        content:"单价",
        subTitle:[
          "不限","1万以下","1-2万"
        ]
      },
      {
        content:"总价",
        subTitle:[
          "不限","80万以下","80-150万"
        ]
      }
    ],
    houseTitle:[
      {
        content:"高层",
        subTitle:[
          "一室一厅","两室一厅","三室一厅"
        ]
      },
      {
        content:"老居民楼",
        subTitle:[
          "一室一厅","两室一厅","三室一厅"
        ]
      }
    ],
    banner:[
      {
        src:"/images/flower/275x206n(26).jpg"
      },
      {
        src:"/images/flower/275x206n(27).jpg"
      },
      {
        src:"/images/flower/275x206n(28).jpg"
      },
      {
        src:"/images/flower/275x206n(29).jpg"
      },
      {
        src:"/images/flower/275x206n(3).jpg"
      }
    ],
    grid:[
      {
        src:"/images/grid/timg-4.jpeg",
        name:"在售楼盘"
      },
      {
        src:"/images/grid/timg-5.jpeg",
        name:"即将开盘"
      },
      {
        src:"/images/grid/timg-6.jpeg",
        name:"推荐楼盘"
      }
    ],
    house:[
      {
        src:"/images/flower/275x206n(3).jpg",
        name:"花语津郡",
        price:"29700元/平方米",
        tag:[
          "住宅","在售","vr看房"
        ],
        subTitle:[
          "医院","商业街","高绿化率"
        ]
      },
      {
        src:"/images/hoom/372x280n(3).jpg",
        name:"中国铁建公馆189",
        price:"98万元/套起",
        tag:[
          "住宅","项目在建","装修"
        ],
        subTitle:[
          "地区","地区","建面"
        ]
      },
      {
        src:"/images/other/200x150m.jpg",
        name:"中国铁建西派国印･禧阙",
        price:"34000元/平方米",
        tag:[
          "住宅","在售","vr看房"
        ],
        subTitle:[
          "市内六区","大户型","商业街"
        ]
      },
      {
        src:"/images/other/200x150m-2.jpg",
        name:"美的旭辉翰悦府",
        price:"20500元/平方米",
        tag:[
          "住宅","在售",
        ],
        subTitle:[
           "高绿化率","大型社区","全朝南"
        ]
      },
      {
        src:"/images/other/200x150m-3.jpg",
        name:"和融广场·悦湾河畔",
        price:"28000元/平方米",
        tag:[
          "商住"," 在售"
        ],
        subTitle:[
          "装修交付","车位充足","在建"
        ]
      },
      {
        src:"/images/other/200x150m-4.jpg",
        name:"未来城",
        price:"21000元/平方米",
        tag:[
          "住宅","在售",
        ],
        subTitle:[
          "低容积","高绿化率","全朝南"
        ]
      },
      {
        src:"/images/other/200x150m-5.jpg",
        name:"金融街·西青金悦府",
        price:19000,
        tag:[
          "住宅","在售",
        ],
        subTitle:[
          "高绿化率","南北通透","大户型"
        ]
      },
    ]
  },
  //事件处理函数

  onLoad: function () {
    
  },
  onTap(e){
    wx.navigateTo({
      url: `/pages/subpackages/detail/index/index`,
    })
  },
  onNaviCard(){
    wx.navigateTo({
      url: `/pages/subpackages/main/houseList/index`,
    })
  },
  onNaviCard1(){
    wx.navigateTo({
      url: `/pages/subpackages/main/calculator/index`,
    })
  },
  // onPageScroll(res) {
  //   console.log(res)
  //   wx.lin.setScrollTop(res.scrollTop)
  // },
  scroll(res){
    wx.lin.setScrollTop(res.detail.scrollTop)
    this.setData({
      margin:368-res.detail.scrollTop,
    })
  },
  onAre(){
    this.setData({
      showAre:!this.data.showAre,
      showMore:false,
      showHouse:false,
      showPrice:false,
      toView: 'tab',
      isScroll:false
    })
  },
  onMore(){
    this.setData({
      showMore:!this.data.showMore,
      showHouse:false,
      showAre:false,
      showPrice:false,
      toView: 'tab',
      isScroll:false
    })
  },
  onPrice(){
    this.setData({
      showMore:false,
      showHouse:false,
      showAre:false,
      showPrice:!this.data.showPrice,
      toView: 'tab',
      isScroll:false
    })
  },
   onHouse(){
    this.setData({
      showMore:false,
      showHouse:!this.data.showHouse,
      showAre:false,
      showPrice:false,
      toView: 'tab',
      isScroll:false
    })
  },
  submit(){
    wx.navigateTo({
      url: `/pages/subpackages/main/houseList/index`,
    })
  },
  changeTabs(e){
    let Tab = e.detail.activeKey
    this.setData({
      Tab:Tab
    })
  },
  onContent(e){
  
      this.setData({
        tabIndex:e.currentTarget.dataset.index
      })
  },
  scoll(){
    this.setData({
      isScroll:true
    })
  }
})
